import Report from '../models/Report.js';
import { triggerNotification } from '../utils/triggerNotification.js';
import { triggerDoctorNotification } from '../utils/triggerDoctorNotification.js';

export const createReport = async (req, res) => {
  try {
    const doctorId = req.user._id;
    const {
      patientId,
      appointmentId,
      patientName,
      patientIdString,
      ageGender,
      reportType,
      priority,
      visitDate,
      visitTime,
      chiefComplaint,
      symptoms,
      diagnosis,
      clinicalObservations,
      vitalSigns,
      treatmentSummary,
      laboratoryAndImaging,
      followUpAdvice,
      lifestyleAdvice,
      additionalNotes,
      status
    } = req.body;

    if (!patientName || !reportType || !visitDate || !visitTime) {
      return res.status(400).json({ success: false, message: 'Please fill all required fields.' });
    }

    const report = new Report({
      doctorId,
      patientId: patientId || null,
      appointmentId: appointmentId || null,
      patientName,
      patientIdString,
      ageGender,
      reportType,
      priority,
      visitDate,
      visitTime,
      chiefComplaint,
      symptoms,
      diagnosis,
      clinicalObservations,
      vitalSigns,
      treatmentSummary,
      laboratoryAndImaging,
      followUpAdvice,
      lifestyleAdvice,
      additionalNotes,
      status: status || 'Draft'
    });

    await report.save();

    if (patientId) {
      await triggerNotification(
        patientId,
        'Medical',
        'New Medical Report',
        `A new ${reportType} has been generated by your doctor.`,
        'View Report',
        '/patient-history',
        'medium'
      );
    }

    // Notify the doctor as well for confirmation
    await triggerDoctorNotification(
      doctorId,
      'Medical',
      'Report Created Successfully',
      `You have successfully created a ${reportType} for ${patientName}.`,
      'View Reports',
      '/doctordashboard/reports',
      'low'
    );

    res.status(201).json({ success: true, message: 'Report created successfully.', data: report });
  } catch (error) {
    console.error('Error creating report:', error);
    res.status(500).json({ success: false, message: 'Server error', error: error.message });
  }
};

export const getReports = async (req, res) => {
  try {
    const doctorId = req.user._id;
    const reports = await Report.find({ doctorId }).sort({ createdAt: -1 });
    res.status(200).json({ success: true, count: reports.length, data: reports });
  } catch (error) {
    console.error('Error fetching reports:', error);
    res.status(500).json({ success: false, message: 'Server error', error: error.message });
  }
};

export const getReportById = async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found' });
    }
    // Check if the report belongs to the logged in doctor or the patient
    if (report.doctorId.toString() !== req.user._id.toString() && report.patientId?.toString() !== req.user._id.toString()) {
        return res.status(403).json({ success: false, message: 'Not authorized to view this report' });
    }
    res.status(200).json({ success: true, data: report });
  } catch (error) {
    console.error('Error fetching report:', error);
    res.status(500).json({ success: false, message: 'Server error', error: error.message });
  }
};

export const updateReportStatus = async (req, res) => {
  try {
    const doctorId = req.user._id;
    const { id } = req.params;
    const { status } = req.body;

    const allowedStatuses = ['Draft', 'Final', 'Completed', 'Signed'];
    if (!allowedStatuses.includes(status)) {
      return res.status(400).json({ success: false, message: `Invalid status. Must be one of: ${allowedStatuses.join(', ')}` });
    }

    const report = await Report.findOne({ _id: id, doctorId });
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found or not authorized' });
    }

    report.status = status;
    await report.save();

    if (status === 'Final' && report.patientId) {
      const { triggerNotification } = await import('../utils/triggerNotification.js');
      await triggerNotification(
        report.patientId,
        'Medical',
        'Medical Report Published',
        `Your ${report.reportType} has been published by your doctor.`,
        'View Report',
        '/patient-history',
        'medium'
      );
    }

    res.status(200).json({ success: true, message: `Report status updated to ${status}`, data: report });
  } catch (error) {
    console.error('Error updating report status:', error);
    res.status(500).json({ success: false, message: 'Server error', error: error.message });
  }
};

export const updateReport = async (req, res) => {
  try {
    const doctorId = req.user._id;
    const { id } = req.params;
    const updateFields = req.body;

    const report = await Report.findOne({ _id: id, doctorId });
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found or not authorized' });
    }

    Object.assign(report, updateFields);
    await report.save();

    res.status(200).json({ success: true, message: 'Report updated successfully', data: report });
  } catch (error) {
    console.error('Error updating report:', error);
    res.status(500).json({ success: false, message: 'Server error', error: error.message });
  }
};

export const deleteReport = async (req, res) => {
  try {
    const doctorId = req.user._id;
    const { id } = req.params;

    const report = await Report.findOne({ _id: id, doctorId });
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found or not authorized' });
    }

    if (report.status !== 'Draft') {
      return res.status(400).json({ success: false, message: 'Only draft reports can be deleted.' });
    }

    await report.deleteOne();
    res.status(200).json({ success: true, message: 'Report deleted successfully' });
  } catch (error) {
    console.error('Error deleting report:', error);
    res.status(500).json({ success: false, message: 'Server error', error: error.message });
  }
};
