import React, { useEffect, useState } from 'react';
import { FileText, CheckCircle, Upload, AlertTriangle, BarChart3, Calendar as CalendarIcon, ChevronDown, ArrowRight, TrendingUp, FileSpreadsheet, ArrowDown, Loader2 } from 'lucide-react';
import { ResponsiveContainer, PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';
import { Link } from 'react-router-dom';
import LabHeader from './LabHeader';
import { labService } from '../services/labService';

const emptyDashboard = {
  dateLabel: '',
  stats: {},
  todayRequests: [],
  urgentRequests: [],
  statusOverview: { total: 0, items: [] },
  testsByCategory: [],
  recentlyUploaded: [],
};
const statConfig = [
  ['pendingTestRequests', 'Pending Test Requests', FileText, 'blue'],
  ['testsCompletedToday', 'Tests Completed Today', CheckCircle, 'emerald'],
  ['reportsAwaitingUpload', 'Reports Awaiting Upload', Upload, 'amber'],
  ['urgentTests', 'Urgent Tests', AlertTriangle, 'rose'],
  ['totalTestsThisMonth', 'Total Tests This Month', BarChart3, 'indigo'],
];
const priorityStyle = (priority) => priority === 'Urgent' ? 'bg-red-50 text-red-600 border-red-100' : priority === 'High' ? 'bg-amber-50 text-amber-600 border-amber-100' : 'bg-emerald-50 text-emerald-600 border-emerald-100';
const cardColors = (color) => ({
  blue: { bg: 'bg-blue-50 text-blue-600', trend: 'text-blue-600' }, emerald: { bg: 'bg-emerald-50 text-emerald-600', trend: 'text-emerald-600' },
  amber: { bg: 'bg-amber-50 text-amber-600', trend: 'text-amber-600' }, rose: { bg: 'bg-red-50 text-red-600', trend: 'text-red-500 font-bold' },
  indigo: { bg: 'bg-indigo-50 text-indigo-600', trend: 'text-gray-400' },
}[color] || { bg: 'bg-gray-50 text-gray-600', trend: 'text-gray-500' });
const statusBadge = (status) => status === 'Completed' ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : status === 'Cancelled' ? 'bg-gray-100 text-gray-500 border-gray-200' : 'bg-blue-50 text-blue-600 border-blue-100';

const LabDashboard = () => {
  const [dashboard, setDashboard] = useState(emptyDashboard);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const localUser = (() => { try { return JSON.parse(localStorage.getItem('user') || '{}'); } catch { return {}; } })();

  useEffect(() => {
    const fetchDashboard = async () => {
      try {
        setLoading(true); setError('');
        const res = await labService.getDashboard();
        if (res.success) setDashboard({ ...emptyDashboard, ...res.data });
      } catch (err) {
        console.error(err); setError('Failed to load dashboard data.');
      } finally { setLoading(false); }
    };
    fetchDashboard();
  }, []);

  const stats = statConfig.map(([key, title, icon, color]) => ({ key, title, icon, color, ...(dashboard.stats?.[key] || { value: 0, change: 'No data', trendType: 'neutral' }) }));
  const donutData = dashboard.statusOverview?.items || [];
  const barData = dashboard.testsByCategory || [];

  return <div className="min-h-screen bg-gray-50/50 pb-12"><LabHeader activePage="dashboard" /><main className="max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 mt-6">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-gray-900">Dashboard</h1><p className="text-sm text-gray-500 mt-0.5">Welcome back, {localUser?.fullName?.split(' ')?.[0] || 'Lab Technician'}! Here's what's happening in the lab today.</p></div><div className="flex items-center gap-2 bg-white border border-gray-100 px-4 py-2.5 rounded-xl shadow-sm text-sm font-semibold text-gray-700 self-start md:self-auto"><CalendarIcon className="w-4 h-4 text-gray-400" /><span>{dashboard.dateLabel || new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric', weekday: 'long' })}</span><ChevronDown className="w-4 h-4 text-gray-400 ml-1" /></div></div>
    {error && <div className="mb-5 bg-red-50 border border-red-100 text-red-600 rounded-xl px-4 py-3 text-sm font-semibold">{error}</div>}
    {loading ? <div className="bg-white border border-gray-100 rounded-2xl p-12 flex items-center justify-center gap-2 text-gray-500 font-semibold"><Loader2 className="w-6 h-6 animate-spin text-[#00B9D6]" />Loading dashboard...</div> : <>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-5 mb-8">{stats.map(stat => { const classes = cardColors(stat.color), Icon = stat.icon; return <div key={stat.key} className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm hover:shadow-md transition-all duration-300 flex flex-col justify-between"><div><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${classes.bg}`}><Icon className="w-5 h-5" /></div><p className="text-xs font-semibold text-gray-400 mt-4 leading-tight">{stat.title}</p><p className="text-3xl font-extrabold text-gray-900 mt-2">{stat.value}</p></div><div className={`text-xs mt-3 flex items-center gap-1 ${classes.trend}`}>{stat.trendType === 'up' && <TrendingUp className="w-3.5 h-3.5" />}{stat.trendType === 'down' && <ArrowDown className="w-3.5 h-3.5 text-amber-500" />}<span>{stat.change}</span></div></div>; })}</div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8"><div className="lg:col-span-2 bg-white border border-gray-100 rounded-2xl shadow-sm p-6 flex flex-col justify-between"><div><div className="flex items-center justify-between mb-5"><h2 className="text-base font-bold text-gray-800">Today's Test Requests</h2><Link to="/lab/requests" className="text-sm font-bold text-blue-600 hover:text-blue-700 transition-colors">View All</Link></div><div className="overflow-x-auto -mx-6"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-gray-100 bg-gray-50/50 text-[10px] uppercase font-bold tracking-wider text-gray-400"><th className="py-3 px-6">Request ID</th><th className="py-3 px-6">Patient Name</th><th className="py-3 px-6">Test</th><th className="py-3 px-6 text-center">Priority</th><th className="py-3 px-6">Requested Time</th><th className="py-3 px-6">Status</th></tr></thead><tbody className="divide-y divide-gray-50">{dashboard.todayRequests.length ? dashboard.todayRequests.map(req => <tr key={req.id} className="hover:bg-gray-50/50 transition-colors"><td className="py-4 px-6 text-sm font-bold text-blue-600">{req.id}</td><td className="py-4 px-6 text-sm font-medium text-gray-700">{req.name}</td><td className="py-4 px-6 text-sm text-gray-500 font-medium">{req.test}</td><td className="py-4 px-6 text-center"><span className={`inline-block px-2.5 py-1 text-[11px] font-bold rounded-lg border ${priorityStyle(req.priority)}`}>{req.priority}</span></td><td className="py-4 px-6 text-sm text-gray-500 font-semibold">{req.time}</td><td className="py-4 px-6"><span className={`inline-block px-2.5 py-1 text-[11px] font-bold rounded-lg border ${statusBadge(req.status)}`}>{req.status}</span></td></tr>) : <tr><td colSpan="6" className="py-12 text-center text-sm font-semibold text-gray-400">No test requests for today.</td></tr>}</tbody></table></div></div><div className="mt-5 pt-4 border-t border-gray-50 flex justify-center"><Link to="/lab/requests" className="flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 transition-colors"><span>View All Requests</span><ArrowRight className="w-3.5 h-3.5" /></Link></div></div>
        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6 flex flex-col justify-between"><div><div className="flex items-center justify-between mb-5"><h2 className="text-base font-bold text-gray-800">Urgent Requests</h2><Link to="/lab/requests" className="text-sm font-bold text-blue-600 hover:text-blue-700 transition-colors">View All</Link></div><div className="space-y-4">{dashboard.urgentRequests.length ? dashboard.urgentRequests.map(req => <div key={req.id} className="border border-red-100 bg-red-50/20 rounded-xl p-4 flex items-start justify-between relative overflow-hidden group hover:shadow-sm transition-shadow"><div className="absolute left-0 top-0 bottom-0 w-1 bg-red-500"></div><div><div className="flex items-center gap-1.5"><span className="text-xs font-bold text-red-600 bg-red-50 border border-red-100 px-1.5 py-0.5 rounded-md">Urgent</span><span className="text-xs font-bold text-gray-800">{req.id}</span></div><h4 className="text-sm font-bold text-gray-900 mt-1">{req.name}</h4><p className="text-xs text-gray-500 font-medium mt-0.5">{req.test}</p></div><span className="text-[10px] font-bold text-red-500">{req.time}</span></div>) : <p className="py-8 text-center text-sm font-semibold text-gray-400">No urgent requests.</p>}</div></div><div className="mt-5 pt-4 border-t border-gray-50 flex justify-center"><Link to="/lab/requests" className="flex items-center gap-1.5 text-xs font-bold text-red-600 hover:text-red-700 transition-colors"><span>View All Urgent</span><ArrowRight className="w-3.5 h-3.5" /></Link></div></div></div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"><div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6 flex flex-col justify-between"><div><div className="flex items-center justify-between mb-5"><h2 className="text-base font-bold text-gray-800">Test Status Overview</h2><div className="flex items-center gap-1 bg-gray-50 border border-gray-100 px-2.5 py-1 rounded-lg text-xs font-bold text-gray-600"><span>Today</span><ChevronDown className="w-3.5 h-3.5 text-gray-400" /></div></div><div className="flex flex-col sm:flex-row items-center gap-6"><div className="w-36 h-36 relative flex-shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={donutData} cx="50%" cy="50%" innerRadius={50} outerRadius={65} paddingAngle={3} dataKey="value">{donutData.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none"><span className="text-2xl font-extrabold text-gray-900 leading-none">{dashboard.statusOverview.total}</span><span className="text-[10px] font-semibold text-gray-400 mt-1 uppercase tracking-wider">Total Tests</span></div></div><div className="flex-1 w-full space-y-1.5">{donutData.length ? donutData.map(item => <div key={item.name} className="flex items-center justify-between text-xs"><div className="flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: item.color }}></span><span className="font-semibold text-gray-500">{item.name}</span></div><span className="font-bold text-gray-800">{item.value} ({item.percentage})</span></div>) : <p className="text-sm font-semibold text-gray-400 text-center">No status data.</p>}</div></div></div></div>
        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6 flex flex-col justify-between"><div><div className="flex items-center justify-between mb-5"><div className="flex items-baseline gap-1.5"><h2 className="text-base font-bold text-gray-800">Tests by Category</h2><span className="text-xs text-gray-400 font-semibold">(This Month)</span></div><Link to="/lab/history" className="text-xs font-bold text-blue-600 hover:text-blue-700 transition-colors">View Report</Link></div><div className="h-44 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={barData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#9CA3AF', fontSize: 10, fontWeight: 600 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#9CA3AF', fontSize: 10, fontWeight: 600 }} /><Tooltip cursor={{ fill: 'transparent' }} /><Bar dataKey="value" radius={[4, 4, 0, 0]} barSize={24}>{barData.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.fill} />)}</Bar></BarChart></ResponsiveContainer></div><div className="grid grid-cols-5 gap-2 mt-4 text-center border-t border-gray-50 pt-3">{barData.length ? barData.slice(0, 5).map(item => <div key={item.name}><p className="text-[11px] font-extrabold text-gray-800">{item.value}</p><p className="text-[9px] text-gray-400 font-bold truncate mt-0.5" title={item.name}>{item.name}</p></div>) : <p className="col-span-5 text-sm font-semibold text-gray-400">No category data.</p>}</div></div></div>
        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6 flex flex-col justify-between"><div><div className="flex items-center justify-between mb-5"><h2 className="text-base font-bold text-gray-800">Recently Uploaded Reports</h2><Link to="/lab/results" className="text-sm font-bold text-blue-600 hover:text-blue-700 transition-colors">View All</Link></div><div className="space-y-3.5">{dashboard.recentlyUploaded.length ? dashboard.recentlyUploaded.map(report => <div key={report.id} className="flex items-center justify-between hover:bg-gray-50/50 p-1.5 rounded-lg transition-colors"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600"><FileSpreadsheet className="w-4 h-4" /></div><div><h4 className="text-xs font-bold text-gray-800">{report.id}</h4><p className="text-[10px] text-gray-500 font-semibold mt-0.5">{report.name} • {report.test}</p></div></div><span className="text-[10px] text-gray-400 font-bold">{report.time}</span></div>) : <p className="py-8 text-center text-sm font-semibold text-gray-400">No uploaded reports yet.</p>}</div></div></div></div>
    </>}</main></div>;
};
export default LabDashboard;
