import React, { useEffect, useMemo, useState } from 'react';
import { Search, ChevronDown, Download, Eye, CheckCircle2, AlertTriangle, X, RefreshCw, ThumbsDown, Loader2 } from 'lucide-react';
import LabHeader from './LabHeader';
import { labService } from '../services/labService';
import { normalizeHistory, Pager, ReportModal, statusBadge } from './labResultShared';

export default function LabHistory() {
  const [tab, setTab] = useState('All History'), [search, setSearch] = useState(''), [testTypeFilter, setTestTypeFilter] = useState('All Tests'), [statusFilter, setStatusFilter] = useState('All Status'), [sampleFilter, setSampleFilter] = useState('All Sample Types');
  const [currentPage, setCurrentPage] = useState(1), [history, setHistory] = useState([]), [selectedRecord, setSelectedRecord] = useState(null), [fullReport, setFullReport] = useState(null);
  const [stats, setStats] = useState({ all: 0, completed: 0, abnormal: 0 }), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const rowsPerPage = 8;
  const fetchHistory = async () => { try { setLoading(true); setError(''); const res = await labService.getResults({ limit: 500 }); if (res.success) { const mapped = (res.data || []).map(normalizeHistory); setHistory(mapped); setStats(res.stats || { all: mapped.length, completed: mapped.length, abnormal: 0 }); setSelectedRecord(current => !mapped.length ? null : mapped.find(item => item.id === current?.id) || mapped[0]); } } catch (err) { console.error('Failed to fetch lab history', err); setError('Failed to load lab history.'); } finally { setLoading(false); } };
  useEffect(() => { fetchHistory(); }, []);
  useEffect(() => { setCurrentPage(1); }, [tab, search, testTypeFilter, statusFilter, sampleFilter]);
  const testTypeOptions = useMemo(() => ['All Tests', ...Array.from(new Set(history.map(item => item.type).filter(Boolean)))], [history]);
  const sampleOptions = useMemo(() => ['All Sample Types', ...Array.from(new Set(history.map(item => item.sample).filter(Boolean)))], [history]);
  const tabs = [
    { label: 'All History', count: stats.all || history.length, icon: null, color: '' }, { label: 'Completed', count: stats.completed || 0, icon: CheckCircle2, color: 'text-emerald-500' },
    { label: 'Abnormal', count: stats.abnormal || 0, icon: AlertTriangle, color: 'text-red-400' }, { label: 'Cancelled', count: 0, icon: X, color: 'text-gray-400' }, { label: 'Replaced', count: 0, icon: RefreshCw, color: 'text-orange-400' }, { label: 'Rejected', count: 0, icon: ThumbsDown, color: 'text-red-500' },
  ];
  const summary = [ ['Total Tests', stats.all || history.length, 'text-blue-600'], ['Completed', stats.completed || 0, 'text-emerald-500'], ['Abnormal', stats.abnormal || 0, 'text-red-500'], ['Cancelled', 0, 'text-gray-500'], ['Replaced', 0, 'text-orange-500'], ['Rejected', 0, 'text-red-400'] ];
  const filtered = history.filter(item => {
    const q = search.toLowerCase();
    return (tab === 'All History' || item.status === tab) && (statusFilter === 'All Status' || item.status === statusFilter) && (testTypeFilter === 'All Tests' || item.type === testTypeFilter) && (sampleFilter === 'All Sample Types' || item.sample === sampleFilter) && (!q || item.patient.toLowerCase().includes(q) || item.pid.toLowerCase().includes(q) || item.id.toLowerCase().includes(q) || item.type.toLowerCase().includes(q));
  });
  const totalPages = Math.ceil(filtered.length / rowsPerPage), safePage = Math.min(currentPage, totalPages || 1), paginated = filtered.slice((safePage - 1) * rowsPerPage, safePage * rowsPerPage);
  const recentActivity = history.slice(0, 3).map(item => ({ text: `${item.type} for ${item.patient}`, sub: `${item.status} | ${item.resDate || 'Awaiting result date'}` }));
  const openFullReport = (record) => { setSelectedRecord(record); setFullReport(record); };
  return <div className="min-h-screen bg-gray-50/50 pb-12"><LabHeader activePage="history" /><main className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 mt-6"><div className="mb-5"><h1 className="text-2xl font-extrabold text-gray-900">Test History</h1><p className="text-sm text-gray-400 font-medium mt-0.5">View history of all processed laboratory tests.</p></div>
    <div className="bg-white border border-gray-100 rounded-2xl p-4 mb-5 shadow-sm flex flex-wrap gap-3 items-end"><div className="relative flex-1 min-w-44"><Search className="w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 -translate-y-1/2" /><input placeholder="Search by Patient Name, ID or Test ID..." value={search} onChange={e => setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2.5 text-sm border border-gray-200 rounded-xl bg-gray-50/50 outline-none focus:ring-2 focus:ring-[#00B9D6]/30 focus:border-[#00B9D6] transition-all" /></div>
      <div className="min-w-36"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Date Range</p><div className="flex items-center justify-between gap-1.5 border border-gray-200 rounded-xl px-3 py-2.5 bg-white text-xs font-bold text-gray-700"><span>All completed history</span><ChevronDown className="w-3.5 h-3.5 text-gray-400 flex-shrink-0" /></div></div>
      <div className="min-w-36"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Test Type</p><div className="border border-gray-200 rounded-xl px-3 py-2.5 bg-white"><select value={testTypeFilter} onChange={e => setTestTypeFilter(e.target.value)} className="w-full text-xs font-bold text-gray-700 bg-transparent outline-none">{testTypeOptions.map(option => <option key={option}>{option}</option>)}</select></div></div>
      <div className="min-w-36"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Status</p><div className="border border-gray-200 rounded-xl px-3 py-2.5 bg-white"><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="w-full text-xs font-bold text-gray-700 bg-transparent outline-none"><option>All Status</option><option>Completed</option><option>Abnormal</option></select></div></div>
      <div className="min-w-36"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Sample Type</p><div className="border border-gray-200 rounded-xl px-3 py-2.5 bg-white"><select value={sampleFilter} onChange={e => setSampleFilter(e.target.value)} className="w-full text-xs font-bold text-gray-700 bg-transparent outline-none">{sampleOptions.map(option => <option key={option}>{option}</option>)}</select></div></div>
      <button className="flex items-center gap-2 border border-[#00B9D6] text-[#00B9D6] hover:bg-[#00B9D6] hover:text-white text-xs font-bold px-4 py-2.5 rounded-xl transition-all shadow-sm self-end"><Download className="w-3.5 h-3.5" />Export History</button></div>
    {error && <div className="mb-5 bg-red-50 border border-red-100 text-red-600 rounded-xl px-4 py-3 text-sm font-semibold">{error}</div>}
    <div className="flex gap-5 items-start"><div className="flex-1 bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><div className="flex items-center gap-0 px-4 pt-4 border-b border-gray-100 overflow-x-auto">{tabs.map(t => <button key={t.label} onClick={() => setTab(t.label)} className={`flex items-center gap-1.5 pb-3 px-3 text-xs font-bold border-b-2 transition-colors whitespace-nowrap ${tab === t.label ? 'border-[#00B9D6] text-[#00B9D6]' : 'border-transparent text-gray-400 hover:text-gray-600'}`}>{t.icon && <t.icon className={`w-3.5 h-3.5 ${t.color}`} />}{t.label}<span className={`px-1.5 py-0.5 rounded-full text-[10px] font-bold ${tab === t.label ? 'bg-[#00B9D6] text-white' : 'bg-gray-100 text-gray-500'}`}>{t.count}</span></button>)}</div>
      <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-gray-50">{['Test ID', 'Patient Name', 'Test Type', 'Sample Type', 'Request Date', 'Result Date', 'Status', 'Technician', 'Action'].map(h => <th key={h} className="py-3 px-4 text-[10px] uppercase tracking-wider font-bold text-gray-400">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-50">{loading ? <tr><td colSpan="9" className="py-14 text-center text-gray-400 font-semibold text-sm"><div className="flex items-center justify-center gap-2"><Loader2 className="w-5 h-5 animate-spin text-[#00B9D6]" />Loading history...</div></td></tr> : paginated.map(record => <tr key={`${record.dbId}-${record.testId}`} onClick={() => setSelectedRecord(record)} className={`hover:bg-blue-50/20 transition-colors cursor-pointer ${selectedRecord?.id === record.id ? 'bg-blue-50/40' : ''}`}><td className="py-4 px-4 text-xs font-bold text-gray-700">{record.id}</td><td className="py-4 px-4 text-sm font-bold text-gray-900">{record.patient}</td><td className="py-4 px-4 text-xs font-semibold text-gray-600">{record.type}</td><td className="py-4 px-4 text-xs font-semibold text-gray-600">{record.sample}</td><td className="py-4 px-4 text-xs text-gray-500 font-semibold">{record.reqDate}</td><td className="py-4 px-4 text-xs text-gray-500 font-semibold">{record.resDate || 'Awaiting'}</td><td className="py-4 px-4"><span className={`px-2.5 py-1 text-[11px] font-bold rounded-lg ${statusBadge(record.status)}`}>{record.status}</span></td><td className="py-4 px-4 text-xs font-semibold text-gray-600">{record.tech}</td><td className="py-4 px-4"><button onClick={(e) => { e.stopPropagation(); openFullReport(record); }} className="text-[#00B9D6] hover:bg-blue-50 p-1.5 rounded-lg transition-colors" title="View Report"><Eye className="w-4 h-4" /></button></td></tr>)}{!loading && paginated.length === 0 && <tr><td colSpan="9" className="py-14 text-center text-gray-400 font-semibold text-sm">No records found.</td></tr>}</tbody></table></div>
      <div className="px-5 py-3.5 border-t border-gray-50 flex items-center justify-between"><p className="text-xs text-gray-400 font-semibold">Showing {filtered.length === 0 ? 0 : (safePage - 1) * rowsPerPage + 1} to {Math.min(safePage * rowsPerPage, filtered.length)} of {filtered.length} results</p><Pager total={filtered.length} page={currentPage} rowsPerPage={rowsPerPage} onPage={setCurrentPage} /></div></div>
      <div className="w-64 flex-shrink-0 space-y-4"><div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-5"><h3 className="text-sm font-bold text-gray-900 mb-4">History Summary</h3><div className="space-y-3">{summary.map(([label, val, color]) => <div key={label} className="flex items-center justify-between text-xs font-semibold"><span className="text-gray-500">{label}</span><span className={`font-extrabold ${color}`}>{val}</span></div>)}</div></div>
      <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-5"><h3 className="text-sm font-bold text-gray-900 mb-4">Recent Activity</h3><div className="space-y-3">{recentActivity.length > 0 ? recentActivity.map((activity, i) => <div key={i} className="flex items-start gap-2"><span className="w-2 h-2 rounded-full bg-emerald-400 mt-1 flex-shrink-0" /><div><p className="text-xs font-bold text-gray-800">{activity.text}</p><p className="text-[10px] text-gray-400 font-semibold">{activity.sub}</p></div></div>) : <p className="text-xs font-semibold text-gray-400">No recent activity.</p>}</div></div></div></div></main><ReportModal item={fullReport} onClose={() => setFullReport(null)} /></div>;
}