import React, { useEffect, useMemo, useState } from 'react';
import { Search, Download, Eye, ChevronDown, CheckCircle2, Clock, AlertTriangle, Hourglass, Loader2 } from 'lucide-react';
import LabHeader from './LabHeader';
import { labService } from '../services/labService';
import { normalizeResult, Pager, ReportModal, ResultDetailPanel, statusBadge } from './labResultShared';

const LabResults = () => {
  const [activeTab, setActiveTab] = useState('All Results'), [search, setSearch] = useState(''), [testTypeFilter, setTestTypeFilter] = useState('All Tests'), [statusFilter, setStatusFilter] = useState('All Status');
  const [selectedResult, setSelectedResult] = useState(null), [currentPage, setCurrentPage] = useState(1), [results, setResults] = useState([]), [fullReport, setFullReport] = useState(null);
  const [stats, setStats] = useState({ all: 0, completed: 0, inReview: 0, abnormal: 0, pending: 0 }), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const rowsPerPage = 5;
  const fetchResults = async () => { try { setLoading(true); setError(''); const res = await labService.getResults({ limit: 500 }); if (res.success) { const mapped = (res.data || []).map(normalizeResult); setResults(mapped); setStats(res.stats || { all: mapped.length, completed: mapped.length, inReview: 0, abnormal: 0, pending: 0 }); setSelectedResult(current => !mapped.length ? null : mapped.find(item => item.id === current?.id) || mapped[0]); } } catch (err) { console.error('Failed to fetch lab results', err); setError('Failed to load lab results.'); } finally { setLoading(false); } };
  useEffect(() => { fetchResults(); }, []);
  useEffect(() => { setCurrentPage(1); }, [activeTab, search, testTypeFilter, statusFilter]);
  const testTypeOptions = useMemo(() => ['All Tests', ...Array.from(new Set(results.map(result => result.testType).filter(Boolean)))], [results]);
  const tabFilters = [
    { key: 'All Results', count: stats.all || results.length, icon: null }, { key: 'Completed', count: stats.completed || 0, icon: CheckCircle2, color: 'text-emerald-500' },
    { key: 'In Review', count: stats.inReview || 0, icon: Clock, color: 'text-amber-500' }, { key: 'Abnormal', count: stats.abnormal || 0, icon: AlertTriangle, color: 'text-red-500' }, { key: 'Pending', count: stats.pending || 0, icon: Hourglass, color: 'text-blue-400' },
  ];
  const filtered = results.filter(r => {
    const q = search.toLowerCase();
    return (activeTab === 'All Results' || r.status === activeTab) && (statusFilter === 'All Status' || r.status === statusFilter) && (testTypeFilter === 'All Tests' || r.testType === testTypeFilter) && (!q || r.patient.toLowerCase().includes(q) || r.pid.toLowerCase().includes(q) || r.id.toLowerCase().includes(q) || r.testType.toLowerCase().includes(q));
  });
  const totalPages = Math.ceil(filtered.length / rowsPerPage), safePage = Math.min(currentPage, totalPages || 1), paginated = filtered.slice((safePage - 1) * rowsPerPage, safePage * rowsPerPage);
  const openFullReport = (result) => { setSelectedResult(result); setFullReport(result); };
  return <div className="min-h-screen bg-gray-50/50 pb-12"><LabHeader activePage="results" /><main className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 mt-6"><div className="bg-white border border-dashed border-[#00B9D6]/50 rounded-2xl p-5 mb-5 shadow-sm"><h1 className="text-2xl font-extrabold text-gray-900">Test Results</h1><p className="text-sm text-gray-400 font-medium mt-0.5">View and manage all laboratory test results.</p></div>
    <div className="bg-white border border-gray-100 rounded-2xl p-4 mb-5 shadow-sm"><div className="flex flex-wrap items-end gap-4"><div className="relative flex-1 min-w-48"><Search className="w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 -translate-y-1/2" /><input type="text" placeholder="Search by Patient Name, ID or Test ID..." value={search} onChange={e => setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2.5 text-sm border border-gray-200 rounded-xl bg-gray-50/50 outline-none focus:ring-2 focus:ring-[#00B9D6]/30 focus:border-[#00B9D6] focus:bg-white transition-all" /></div>
      <div className="min-w-44"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Date Range</p><div className="flex items-center justify-between gap-2 border border-gray-200 rounded-xl px-3 py-2.5 bg-white cursor-default"><span className="text-xs font-bold text-gray-700">All completed results</span><ChevronDown className="w-3.5 h-3.5 text-gray-400 flex-shrink-0" /></div></div>
      <div className="min-w-36"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Test Type</p><div className="flex items-center justify-between gap-2 border border-gray-200 rounded-xl px-3 py-2.5 bg-white"><select value={testTypeFilter} onChange={e => setTestTypeFilter(e.target.value)} className="text-xs font-bold text-gray-700 bg-transparent outline-none cursor-pointer w-full">{testTypeOptions.map(option => <option key={option}>{option}</option>)}</select></div></div>
      <div className="min-w-32"><p className="text-[9px] uppercase tracking-wider font-bold text-gray-400 mb-1">Status</p><div className="flex items-center gap-2 border border-gray-200 rounded-xl px-3 py-2.5 bg-white"><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="text-xs font-bold text-gray-700 bg-transparent outline-none cursor-pointer w-full"><option>All Status</option><option>Completed</option><option>Abnormal</option></select></div></div>
      <button className="flex items-center gap-2 bg-white border border-[#00B9D6] text-[#00B9D6] hover:bg-[#00B9D6] hover:text-white text-xs font-bold px-4 py-2.5 rounded-xl transition-all shadow-sm self-end"><Download className="w-3.5 h-3.5" />Export Report</button></div></div>
    {error && <div className="mb-5 bg-red-50 border border-red-100 text-red-600 rounded-xl px-4 py-3 text-sm font-semibold">{error}</div>}
    <div className="flex gap-5 items-start"><div className="flex-1 bg-white border border-dashed border-[#00B9D6]/40 rounded-2xl shadow-sm overflow-hidden"><div className="flex items-center gap-0 px-4 pt-4 border-b border-gray-100 overflow-x-auto">{tabFilters.map(tab => <button key={tab.key} onClick={() => setActiveTab(tab.key)} className={`flex items-center gap-1.5 pb-3 px-3 text-xs font-bold border-b-2 transition-colors whitespace-nowrap ${activeTab === tab.key ? 'border-[#00B9D6] text-[#00B9D6]' : 'border-transparent text-gray-400 hover:text-gray-600'}`}>{tab.icon && <tab.icon className={`w-3.5 h-3.5 ${tab.color}`} />}{tab.key}<span className={`ml-0.5 px-1.5 py-0.5 rounded-full text-[10px] font-bold ${activeTab === tab.key ? 'bg-[#00B9D6] text-white' : 'bg-gray-100 text-gray-500'}`}>{tab.count}</span></button>)}</div>
      <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-gray-50">{['Test ID', 'Patient Name', 'Test Type', 'Sample Type', 'Result Date', 'Status', 'Action'].map(h => <th key={h} className="py-3 px-5 text-[10px] uppercase tracking-wider font-bold text-gray-400">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-50">{loading ? <tr><td colSpan="7" className="py-14 text-center text-gray-400 font-semibold text-sm"><div className="flex items-center justify-center gap-2"><Loader2 className="w-5 h-5 animate-spin text-[#00B9D6]" />Loading results...</div></td></tr> : paginated.map(result => <tr key={`${result.dbId}-${result.testId}`} className={`hover:bg-blue-50/30 transition-colors cursor-pointer ${selectedResult?.id === result.id ? 'bg-blue-50/40' : ''}`} onClick={() => setSelectedResult(result)}><td className="py-4 px-5 text-xs font-bold text-gray-700">{result.id}</td><td className="py-4 px-5 text-sm font-bold text-gray-900">{result.patient}</td><td className="py-4 px-5 text-xs font-semibold text-gray-600 leading-tight">{result.testType}</td><td className="py-4 px-5 text-xs font-semibold text-gray-600">{result.sampleType}</td><td className="py-4 px-5 text-xs font-semibold text-gray-600 leading-tight">{result.resultDate || 'Awaiting'}</td><td className="py-4 px-5"><span className={`inline-block px-2.5 py-1 text-[11px] font-bold rounded-lg ${statusBadge(result.status)}`}>{result.status}</span></td><td className="py-4 px-5"><button onClick={(e) => { e.stopPropagation(); openFullReport(result); }} className="text-[#00B9D6] hover:bg-blue-50 p-1.5 rounded-lg transition-colors" title="View Report"><Eye className="w-4 h-4" /></button></td></tr>)}{!loading && paginated.length === 0 && <tr><td colSpan="7" className="py-14 text-center text-gray-400 font-semibold text-sm">No completed results found.</td></tr>}</tbody></table></div>
      <div className="px-5 py-3.5 border-t border-gray-50 flex items-center justify-between"><p className="text-xs text-gray-400 font-semibold">Showing {filtered.length === 0 ? 0 : (safePage - 1) * rowsPerPage + 1} to {Math.min(safePage * rowsPerPage, filtered.length)} of {filtered.length} results</p><Pager total={filtered.length} page={currentPage} rowsPerPage={rowsPerPage} onPage={setCurrentPage} /></div></div>{selectedResult && <ResultDetailPanel result={selectedResult} onClose={() => setSelectedResult(null)} onViewFullReport={() => openFullReport(selectedResult)} />}</div></main><ReportModal item={fullReport} onClose={() => setFullReport(null)} /></div>;
};
export default LabResults;